<?php

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
$template_directory = get_template_directory();

require( $template_directory . '/core/includes/functions.php' );
require( $template_directory . '/core/includes/functions-update.php' );
require( $template_directory . '/core/includes/functions-sidebar.php' );
require( $template_directory . '/core/includes/functions-install.php' );
require( $template_directory . '/core/includes/functions-admin.php' );
require( $template_directory . '/core/includes/functions-extras.php' );
require( $template_directory . '/core/includes/functions-extentions.php' );
require( $template_directory . '/core/includes/theme-options/theme-options.php' );
require( $template_directory . '/core/includes/post-custom-meta.php' );
require( $template_directory . '/core/includes/tha-theme-hooks.php' );
require( $template_directory . '/core/includes/hooks.php' );
require( $template_directory . '/core/includes/version.php' );
require( $template_directory . '/core/includes/upsell/theme-upsell.php' );

// Return value of the supplied responsive free theme option.
function responsive_free_get_option($option, $default = false) {
    global $responsive_options;

// If the option is set then return it's value, otherwise return false.
    if (isset($responsive_options[$option])) {
        return $responsive_options[$option];
    }

    return $default;
}

//Search in header
function wpgyan_widgets_init() {

    register_sidebar(array(
        'name' => 'Header Widget',
        'id' => 'header_sidebar',
        'before_widget' => '<div>',
        'after_widget' => '</div>',
        'before_title' => '<h2 class="rounded">',
        'after_title' => '</h2>',
    ));
}

add_action('widgets_init', 'wpgyan_widgets_init');

//Cookie
function set_new_cookie() {
    if (isset($_GET['submit_question'])) {
// cookies aanmaken/overschrijven        
        if ($_GET['auto'] == 'ja') {
            if ($_GET['lopen'] == 'ja') { //WEL auto, WEL lopen
                setcookie('mobiliteit', 'wel.wel', time() + 30);
            }
            if ($_GET['lopen'] == 'nee') { // WEL Auto, NIET Lopen
                setcookie('mobiliteit', 'wel.niet', time() + 30);
            }
        }
        if ($_GET['auto'] == 'nee') {
            if ($_GET['lopen'] == 'ja') { //NIET auto, WEL lopen
                setcookie('mobiliteit', 'niet.wel', time() + 30);
            }
            if ($_GET['lopen'] == 'nee') { // NIET Auto, NIET Lopen
                setcookie('mobiliteit', 'niet.niet', time() + 30);
            }
        }
    }
}
add_action('init', 'set_new_cookie');
